name: Build Dummy AAB

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install CMake 4.1.0
        run: |
          yes | ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --licenses
          ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager "cmake;4.1.0"

      - name: Build AAB
        run: |
          chmod +x gradlew
          ./gradlew :hello-jni:app:bundleDebug

      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dummy-app-bundle
          path: hello-jni/app/build/outputs/bundle/debug/app-debug.aab
